[build]
  command = "npm install --force && npm run build"
  publish = "public"

[[headers]]
  # Definiera cache policy för HTML-filer
  for = "/*.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Definiera cache policy för CSS, JS och bilder
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
